---
title: "Projects"
---

# My Projects

Here are my research projects and work:

## Final Report

#### My final project for CELL 6351 - Intro to Reproducible Data Analysis Using R

*Our lab has obtained plasma samples from patients who were infected with COVID-19 between the months of May and November 2020. We ran the plasma over an immunoaffinity purification column with a pan-class I antibody to extract soluble HLA (sHLA), and we eluted the sHLA in acid to denature the MHC molecules and obtain peptides presented by class I sHLA. The eluate was then run through high-performance liquid chromatography (HPLC) to fractionate based on hydrophobicity and separate peptides from full proteins. Next, the peptide fractions were run on a time-of-flight (TOF) mass spectrometer to identify peptide sequences and their associated proteins and genes with high-resolution mass accuracy. I plan on doing our typical data cleanup pipeline in R, showing the distribution of peptide lengths, source proteins, and genes to see if we can identify any COVID-19 peptides. Next, I will perform a more thorough mining of the data by 1) Identifying the peptides with the largest overall intensity across all fractions and 2) individual peptides with the highest intensity peaks. From these peptides I will look at their source proteins and genes. I will perform a GO Term analysis, KEGG pathway analysis and Reactome analysis on the top 15 most abundant and highest intensity peptides for viral protein or response signatures.*

[**View Final Report** →](projects/sHLA_covid_peptides.qmd)

---

## Publications
[**View Publications**](projects/publications.qmd)

---

## Posters
[**View Posters**](projects/posters.qmd)

---
